name: pubish

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo check/test/build` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: libxdiffer

      - run: wasm-pack build
        working-directory: libxdiffer
      
      - run: |
          corepack enable
          pnpm install
          pnpm run build
